# Generated by Django 2.2.5 on 2019-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Null'),
        ),
    ]
