# Generated by Django 2.2.5 on 2019-09-17 12:36

import articals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=articals.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
